#服务注册中心
server:
  port: 8761
eureka:
  instance:
    hostname: order-server

  client:
      registerWithEureka: false
      fetchRegistry: false
      serviceUrl:
#        defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
#         集群配置
         defaultZone: http://order-server2:8762/eureka/
  server:
    enable-self-preservation: false
