
server:
  port: 9002
spring:
  application:
    name: order-consumer

#注册地址
eureka:
  client:
    service-url:
      defaultZone: http://order-server:8761/eureka/,http://order-server2:8762/eureka/    # 指定注册中心的地址


#  instance:
#    prefer-ip-address: true #注册中心显示ip
